[package]
name = "tgup"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "tgui"

[dependencies]
prost = "0.12.3"
rand = "0.8.5"
nix = { version = "0.27.1", features = ["socket", "uio"] }

[build-dependencies]
prost-build = "0.12.3"
